name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'master'

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.3
          - 7.4
          - 8.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup php
        uses: nanasess/setup-php@v3.0.6
        with:
          php-version: ${{ matrix.php }}
      - name: download composer
        run: wget https://raw.githubusercontent.com/composer/getcomposer.org/e3e43bde99447de1c13da5d1027545be81736b27/web/installer -O - -q | php -- --quiet
      - name: install dependencies
        run: composer install
      - name: execute unit tests
        run: composer run-script test
